### ISSUE TITLE
Compiled Version

### ISSUE THREAD

**Issue by maxsteinwand** [ColemanSandefur/The-Crew-2-Drag-Bot#1]
Hey, could you add a release as an .jar file? Not familiar with java and would like to use your project :)

Edit: Just compiled and i am missing the images for the bot to work

**Comment by ColemanSandefur** [comment]
Yep, I never compiled it and just realized it won't work compiled as of right now. I just started working on fixing it and should be finished in a few hours at the most.

**Comment by ColemanSandefur** [comment]
There is now a compiled release. This program is not user friendly and I have not made a tutorial or guide just yet. I will start work on that soon.

**Comment by maxsteinwand** [comment]
```
Loading C:/Users/maxst/Downloads/TheCrew2DragBot/The Crew 2 Drag Bot/images/Burn_Location.png
javax.imageio.IIOException: Can't read input file!
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1308)
        at bot.imageDataTypes.ImageDataManager.loadCustomImage(ImageDataManager.java:58)
        at bot.imageDataTypes.ImageDataManager.loadImageDataPoint(ImageDataManager.java:33)
        at bot.imageDataTypes.ImageDataManager.<clinit>(ImageDataManager.java:19)
        at bot.CarShifting.run(CarState.java:18)
```

Happening for the other images aswell. But i will wait for your tutorial then, thank you :)

**Comment by ColemanSandefur** [comment]
I made a quick video to try and help out. Hope it helps! https://youtu.be/H2HRfuobLag

**Comment by maxsteinwand** [comment]
![Burn_location](https://user-images.githubusercontent.com/57699643/109424037-52950600-79e2-11eb-9848-bcdf008971a3.jpg)
![Perfect_Burn](https://user-images.githubusercontent.com/57699643/109424038-532d9c80-79e2-11eb-908a-00b5672ce3fe.jpg)
![Restart_Ref](https://user-images.githubusercontent.com/57699643/109424039-53c63300-79e2-11eb-87f4-05dea3427dcd.jpg)
![Shift_Location](https://user-images.githubusercontent.com/57699643/109424040-53c63300-79e2-11eb-9e24-f3b72474ba02.jpg)
![Skip_Ref](https://user-images.githubusercontent.com/57699643/109424041-545ec980-79e2-11eb-9ff6-f78536826a91.jpg)
![Start_Ref](https://user-images.githubusercontent.com/57699643/109424043-545ec980-79e2-11eb-9b38-2260030cf6bb.jpg)

So i took these Screenshots and did everything you did in the video, but the car is either not accelerating or just keeps holding w. Any tipps? Running game in borderless and 1920x1080, still helpful video. I will try to calibrate again, but did it already 3 times :D

Edit: Still not working, only thing working is the start if i warm up the tires. Tried ~10 Times now, would appreciate it if you can help me a bit more :D Discord: maxst#1337

**Comment by omgitsjan** [comment]
Same problem here. Would love to use it. For me it's not accelerating at all. 

Did everything like you did in the Video. The only thing that is different is that I use .jpg and not .png for the screenshots but the images and location data looks good.

**Comment by ColemanSandefur** [comment]
**Issue:** screenshots need to be .png not .jpg
