### ISSUE TITLE
Option to edit Nitro usage and self correction

### ISSUE THREAD

**Issue by mistermodcreator** [ColemanSandefur/The-Crew-2-Drag-Bot#2]
Can you please add an option to the bot to use Nitro after a user set amount of time? I'm having an issue that the first shifting fails because with this early Nitro my car accelerates too fast. Sure, I can just not use Nitro at all, but then I won't be able to earn the maximum money. Also, it would be nice if there was an option to set how much and in which direction the bot self-corrects.

Thanks for this awsome bot!

**Comment by ColemanSandefur** [comment]
Yes, I'll try adding that

**Comment by mistermodcreator** [comment]
Thank you!

**Comment by ColemanSandefur** [comment]
Sorry for the long delay, I haven't had much time recently, so I haven't gotten around to create a GUI or event test the current commit, but it should be easy enough. Create a file in the main directory (where the .jars, images, and location_data folders are) called `shift_events.txt`. Then open shift events and modify it to your needs.

Each line in `shift_events.txt` represents an event, the first number that you enter is the gear number that will trigger the event. The next number will define how long to wait in milliseconds after we enter the gear to press the key. The next number defines how long to press the key, and the last field is either `shift` or a character (a-z) which is the key to press.

Here is how `shift_events.txt` might look:
1 100 100 shift
5 1500 100 d

The first line states that when we reach 1st gear (which is the start of the race), we will wait 100ms and then press `shift` for 100ms. This line will activate the boost 100ms after the race starts

The second line states that when we reach 5th gear, we will wait for 1500ms and press `d` for 100ms. This would turn the car right slightly.

Once again, I haven't tested it and don't really have the ability to test it right now so I don't really know if this will even work.

**Comment by mistermodcreator** [comment]
Thanks! Can you upload a compiled version too? I'm not really good in programming and because of that can't compile it myself. I'll test it later and then tell you if it works.

**Comment by ColemanSandefur** [comment]
[TheCrew2DragBot.zip](https://github.com/ColemanSandefur/The-Crew-2-Drag-Bot/files/6826427/TheCrew2DragBot.zip)

Here is a compiled version

**Comment by mistermodcreator** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/74619800/125961268-eec2cd54-4f20-4f8d-b4ea-01f39119684f.png)
An Update without an error wouldn't be an update... Any idea about what is wrong and what i can do to fix it?
The bottom text means "Press any Key..."

**Comment by maxsteinwand** [comment]
German: Alte java version, java deinstallieren und nochmal die neuste version installieren da deine aktuelle java version nur bis zu v 55.0 unterstützt, aber die compiled version 59.0 ist.

English: Old java version, uninstall java and install the latest version again as your current java version only supports up to v 55.0 but the compiled version is 59.0.

**Comment by ColemanSandefur** [comment]
[TheCrew2DragBot.zip](https://github.com/ColemanSandefur/The-Crew-2-Drag-Bot/files/6832431/TheCrew2DragBot.zip)
I think I compiled with the wrong Java version, this should work better now

**Comment by mistermodcreator** [comment]
And got an error again. I belief it's something with the way it reads the shift_events.txt file? I attached a screenshot showing the error and my bot files. Thanks for helping me!
[The Crew 2 Drag Bot V2.zip](https://github.com/ColemanSandefur/The-Crew-2-Drag-Bot/files/6864104/The.Crew.2.Drag.Bot.V2.zip)
![Screenshot (33)](https://user-images.githubusercontent.com/74619800/126681860-f4f129d7-a401-46cc-a454-07b60f5dcc51.png)

**Comment by ColemanSandefur** [comment]
You were correct; 
I had a bit of time to make sure that the Shift Events actually worked, although I'm still unsure if they will work when the bot runs. Here is a newer build: 
[TheCrew2DragBot.zip](https://github.com/ColemanSandefur/The-Crew-2-Drag-Bot/files/6866518/TheCrew2DragBot.zip)

**Comment by mistermodcreator** [comment]
Working fine! No errors in about two hours.
