### ISSUE TITLE
shift_events.txt not found error

### ISSUE THREAD

**Issue by Aloalaninja** [ColemanSandefur/The-Crew-2-Drag-Bot#3]
What shift_events.txt there is none and included in the releases download, I created one but am not sure what to put into it
Should be located in the main "The Crew 2 Drag Bot" folder. 
Any help would be appreciated but I doubt anyone will respond.

![Screenshot_20221208_084154](https://user-images.githubusercontent.com/113308777/206603900-33d74cc8-8ba7-4e73-8d84-891aa9d8bb3a.png)
![Screenshot 2022-12-08 204428](https://user-images.githubusercontent.com/113308777/206604144-20a20792-5b74-490a-b795-386a13950878.png)

**Comment by mistermodcreator** [comment]
Hi, I'm still subscribed to this project and I'm the one who first tested this. First, you need to download the last version of the bot sent in #2. Then, you need to follow this instructions, which is a quote from @ColemanSandefur from #2 

> Create a file in the main directory (where the .jars, images, and location_data folders are) called shift_events.txt. Then open shift events and modify it to your needs.
> 
> Each line in shift_events.txt represents an event, the first number that you enter is the gear number that will trigger the event. The next number will define how long to wait in milliseconds after we enter the gear to press the key. The next number defines how long to press the key, and the last field is either shift or a character (a-z) which is the key to press.
> 
> Here is how shift_events.txt might look:
> 1 100 100 shift
> 5 1500 100 d
> 
> The first line states that when we reach 1st gear (which is the start of the race), we will wait 100ms and then press shift for 100ms. This line will activate the boost 100ms after the race starts
> 
> The second line states that when we reach 5th gear, we will wait for 1500ms and press d for 100ms. This would turn the car right slightly.


I hope that answers your question! As far as I know, this feature still is experimental and therefore a little difficult to set up.

**Comment by Aloalaninja** [comment]
Do you have a txt file with the timings for a drag car already set up that you could send? Preferably corvette but any is fine.

**Comment by mistermodcreator** [comment]
I haven't used the software since this feature was released. I can sent you a file, but I don't know for which car or which track I created it.
[shift_events.txt](https://github.com/ColemanSandefur/The-Crew-2-Drag-Bot/files/10197765/shift_events.txt)

**Comment by Aloalaninja** [comment]
Thank you, I just noticed I am stupid and was misunderstanding what the file was used for. I thought file held the time waited between shifting gears not for activating nitro.

**Comment by ColemanSandefur** [comment]
Thanks @mistermodcreator for helping out. This is indeed an experimental feature that I never finished. I'll see if I can make it a bit more intuitive and user friendly over the next few days.

**Comment by mistermodcreator** [comment]
> I'll see if I can make it a bit more intuitive and user friendly over the next few days.

Did you get anywhere? Just stumbled over this again.
